FROM python:3.11

USER root
COPY ./streamlit_langgraph /app
COPY ./.env /app
COPY requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install -r /app/requirements.txt


WORKDIR /app

ENTRYPOINT ["streamlit","run", "/app/streamlit_multi_ai_agent.py"]